import { AfterAll, Before, BeforeAll } from '@cucumber/cucumber';
import { ArtifactArchiver, Cast, configure, engage, TakeNotes } from '@serenity-js/core';
import { BrowseTheWebWithPlaywright } from '@serenity-js/playwright';
import { SerenityBDDReporter } from '@serenity-js/serenity-bdd';
import { Photographer, TakePhotosOfFailures } from '@serenity-js/web';
import * as playwright from 'playwright';
import { BASE_URL } from '../../support/world';

/**
 * Lane A Serenity/JS wiring (design doc §4/§5.1): Playwright-backed browsing, Serenity BDD
 * JSON artefacts into target/site/serenity (HTML generated by `npm run report`, needs Java),
 * screenshots on failure only. Serial execution; the shared hooks in features/support
 * still provide the DR-PB-06 reset bracket and the REST cross-check actor.
 */

let browser: playwright.Browser;

BeforeAll({ timeout: 60_000 }, async function () {
  browser = await playwright.chromium.launch({ headless: true });
  configure({
    crew: [
      ArtifactArchiver.storingArtifactsAt('./target/site/serenity'),
      SerenityBDDReporter.fromJSON({ specDirectory: './features' }),
      Photographer.whoWill(TakePhotosOfFailures)
    ]
  });
});

Before(function () {
  engage(
    Cast.where((actor) =>
      actor.whoCan(
        BrowseTheWebWithPlaywright.using(browser, { baseURL: BASE_URL }),
        TakeNotes.usingAnEmptyNotepad()
      )
    )
  );
});

AfterAll(async function () {
  await browser?.close();
});
